version: "3.7"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always

  php:
    build: .
    container_name: php
    restart: "no"
    ports:
      - 8080:8080
    