version: "3.7"
services:

  devcontainer:
    build: .
    volumes:
      - ../..:/web/CSE442-542/2023-Spring/cse-442g/:cached
    network_mode: service:db
    command: sleep infinity
    environment:
      WAIT_HOSTS: db:3306

    depends_on:
      - db

    
  db:
      image: mysql
      ports:
          - 3306:3306
      command: --default-authentication-plugin=mysql_native_password
      hostname: oceanus.cse.buffalo.edu
      restart: always
      environment:
          MYSQL_USER: sjrichel
          MYSQL_PASSWORD: 50338787
          MYSQL_DATABASE: cse442_2023_spring_team_g_db
          MYSQL_ROOT_PASSWORD: password
      volumes:
          - "test_db:/var/lib/mysql"
          
  # for php myadmin goto http://localhost:8181
  db_admin:
      image: phpmyadmin/phpmyadmin
      ports:
          - 8181:80
      restart: "on-failure"
      depends_on:
          - db
      links:
          - db
      environment:
          PMA_HOST: db
          PMA_PORT: 3306
          PMA_USER: sjrichel
          PMA_PASSWORD: 50338787

volumes:
    test_db: