version: "3.7"
services:

  devcontainer:
    build: .
    volumes:
      - ../..:/web/CSE442-542/2023-Spring/cse-442g/:cached
    network_mode: service:db
    command: sleep infinity
    
  db:
      image: mysql
      ports:
          - 3306:3306
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
          MYSQL_USER: admin
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_PASSWORD: password
      volumes:
          - "test_db:/var/lib/mysql"
          
  # for php myadmin goto http://localhost:8181
  db_admin:
      image: phpmyadmin/phpmyadmin
      ports:
          - 8181:80
      restart: "on-failure"
      depends_on:
          - db
      links:
          - db
      environment:
          PMA_HOST: db
          PMA_PORT: 3306
          PMA_USER: admin
          PMA_PASSWORD: password

volumes:
    test_db: