version: "3.7"
services:
  devcontainer:
    build: .
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:mongoDB
    command: sleep infinity
    
  mongoDB:
    image: mongo:latest
    container_name: mongoDB
    restart: always
    ports:
      - 27017:27017