name: Deploy to Production

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        HOST: 3.84.113.251
        USER: ec2-user
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # SSH commands below
        ssh -o StrictHostKeyChecking=no $USER@$HOST "
          cd /home/ec2-user/nutrio;
          git stash;
          git pull;
        "