name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        HOST: 159.223.186.15
        USER: root
      run: |
        sudo apt-get install -y sshpass
        # SSH commands below
        sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $USER@$HOST "
          cd /root/nutrio;
          git stash;
          git pull;
        "