name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        HOST: 18.118.198.248
        USER: root
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # SSH commands below
        ssh -o StrictHostKeyChecking=no $USER@$HOST "
          cd /home/root/nutrio;
          git stash;
          git pull;
          docker-compose down;
          docker-compose up -d --build --force-recreate;
        "